---
sudo: required
dist: xenial
language: python
python:
  - "2.7"
  - "3.7"
env:
  - ANSIBLE_VERSION="2.6"
  - ANSIBLE_VERSION="2.7"
services:
  - docker
install:
  - pip install tox-travis
script:
  - tox
