---
- name: Include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Sanity check
  assert:
    that:
      - icingaweb2_manage_repo is defined
      - icingaweb2_prerequisites is defined
      - icingaweb2_packages is defined
      - icingaweb2_config_resources_ini is defined
      - icingaweb2_config_config_ini is defined
      - icingaweb2_config_authentication_ini is defined

- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ icingaweb2_prerequisites }}"

- include_tasks: "repository.yml"
  when: icingaweb2_manage_repo

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ icingaweb2_packages }}"

- name: resources.ini
  ini_file:
    path: /etc/icingaweb2/resources.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ icingaweb2_config_resources_ini }}"
  loop_control:
    label: "[{{ item.section }}] {{ item.option }}"

- name: config.ini
  ini_file:
    path: /etc/icingaweb2/config.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ icingaweb2_config_config_ini }}"
  loop_control:
    label: "[{{ item.section }}] {{ item.option }}"

- name: authentication.ini
  ini_file:
    path: /etc/icingaweb2/authentication.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ icingaweb2_config_authentication_ini }}"
  loop_control:
    label: "[{{ item.section }}] {{ item.option }}"
