---
- name: Prepare
  hosts: all
  tasks:
    - name: Install test requirements
      package:
        name: "{{ item }}"
        state: installed
      with_items:
        - openssl
        - epel-release

- name: Prepare webserver
  hosts: all
  roles:
    - role: smbambling.scl
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: geerlingguy.apache-php-fpm
  tasks:
    - name: reload httpd
      service:
        name: httpd.service
        state: reloaded
  vars:
    php_enable_php_fpm: true
    php_date_timezone: 'UTC'

    # Use SCL version of php
    php_conf_paths: /etc/opt/rh/rh-php71
    php_extension_conf_paths: /etc/opt/rh/rh-php71/php.d/
    php_fpm_daemon: rh-php71-php-fpm.service
    php_packages:
      - rh-php71-php-cli
      - rh-php71-php-fpm

- name: Prepare database
  hosts: all
  roles:
    - role: geerlingguy.postgresql
  vars:
    postgresql_databases:
      - name: icinga
      - name: icingaweb2
    postgresql_users:
      - name: icinga
        password: icinga
        db: icinga
      - name: icingaweb2
        password: icingaweb2
        db: icingaweb2
